export * from './DashboardPage';
export * from './HomePage';
export * from './LoginPage';
export * from './RegisterPage';
export * from './Home';
export * from './AcercaDe'
export * from './Configuracion';
export * from './Contacto';
export * from './Perfil';
export * from './Reportes';
export * from './Servicios';